### ISSUE TITLE
Interpret selection and Interpret file not working in Node Repl

### ISSUE THREAD

**Issue by waldnzwrld** [rndAdn/REPL-Nodejs#16]
When using Node Repl, the hotkey bindings to open a new repl `ctrl+y, ctrl+n` function as expected.

However, when the option to interpret a selection or file is chosen either through the menu, or through hotkey combinations `ctrl+y, ctrl+s` `ctrl+y, ctrl+f` is not functioning.

**Comment by vlahm** [comment]
I'm having the same problem with Python3 REPL. Atom version 1.12.7, Ubuntu 14.04.
